#!/bin/sh

set -eu

LAB_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
RESULTS_DIR="$LAB_DIR/results"
CC_BIN=${CC:-cc}
CFLAGS_BIN=${CFLAGS:-"-O2 -g"}

mkdir -p "$RESULTS_DIR"

cat >"$RESULTS_DIR/README.md" <<EOF
# Results

Generated by \`./run.sh\`:

- \`container_of_demo.txt\`: recovered pointer chain and layout numbers
- \`pointer_tagging_demo.txt\`: aligned vs packed pointer tagging evidence
EOF

$CC_BIN $CFLAGS_BIN -std=gnu11 -Wall -Wextra \
    "$LAB_DIR/container_of_demo.c" -o "$LAB_DIR/container_of_demo"
$CC_BIN $CFLAGS_BIN -std=gnu11 -Wall -Wextra \
    "$LAB_DIR/pointer_tagging_demo.c" -o "$LAB_DIR/pointer_tagging_demo"

"$LAB_DIR/container_of_demo" >"$RESULTS_DIR/container_of_demo.txt"
"$LAB_DIR/pointer_tagging_demo" >"$RESULTS_DIR/pointer_tagging_demo.txt"
