#!/usr/bin/env bash
set -u -o pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$ROOT/src"
INCLUDE_DIR="$ROOT/include"
BUILD_DIR="$ROOT/build"
ARTIFACTS_DIR="$ROOT/artifacts"
MATRIX_FILE="$ROOT/compile_matrix.md"

compilers=(gcc clang)

mode_names=(
  "std-c99"
  "std-c11"
  "std-c11-pedantic"
  "opt-O0"
  "opt-O2"
  "strict-aliasing"
  "no-strict-aliasing"
)

mode_flags=(
  "-std=c99"
  "-std=c11"
  "-std=c11 -pedantic"
  "-O0"
  "-O2"
  "-fstrict-aliasing"
  "-fno-strict-aliasing"
)

targets=(
  "portable|layout_portable.c"
  "gnu|layout_gnu.c"
  "c11|layout_c11.c"
)

mkdir -p "$BUILD_DIR" "$ARTIFACTS_DIR"

short_summary() {
  local file="$1"
  local line=""
  if [[ -s "$file" ]]; then
    line="$(grep -m1 -E '(^|[[:space:]])(fatal )?error:' "$file" 2>/dev/null || true)"
    if [[ -z "$line" ]]; then
      line="$(head -n 1 "$file" 2>/dev/null || true)"
    fi
    if [[ -n "$line" ]]; then
      printf '%s' "$line" | sed -E -e 's#^.*(fatal )?error: #error: #' -e 's/[[:space:]]+/ /g' -e 's/\|/\\|/g' | cut -c1-180
      return 0
    fi
  fi
  if [[ -z "$line" ]]; then
    printf 'no diagnostics'
  else
    printf '%s' "$line"
  fi
}

compile_and_run() {
  local compiler="$1"
  local mode_name="$2"
  local mode_flag_string="$3"
  local target_name="$4"
  local source_file="$5"
  local out_dir="$BUILD_DIR/$compiler/$mode_name/$target_name"
  local binary="$out_dir/demo"
  local compile_log="$out_dir/compile.log"
  local run_log="$out_dir/run.log"
  local -a mode_flags
  IFS=' ' read -r -a mode_flags <<<"$mode_flag_string"
  mkdir -p "$out_dir"

  if "$compiler" "${mode_flags[@]}" -I"$INCLUDE_DIR" "$source_file" -o "$binary" >"$compile_log" 2>&1; then
    if "$binary" >"$run_log" 2>&1; then
      printf '| %s | %s | %s | pass | run ok |\n' "$target_name" "$compiler" "$mode_name"
    else
      printf '| %s | %s | %s | fail | run failed: %s |\n' \
        "$target_name" "$compiler" "$mode_name" "$(short_summary "$run_log")"
    fi
  else
    printf '| %s | %s | %s | fail | compile failed: %s |\n' \
      "$target_name" "$compiler" "$mode_name" "$(short_summary "$compile_log")"
  fi
}

write_matrix() {
  {
    printf '# Compile Matrix\n\n'
    printf 'Generated by `./run.sh matrix` on %s.\n\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"
    printf 'This matrix records build-and-run results for the three lab programs across gcc and clang.\n'
    printf 'The C11 source is expected to fail under `-std=c99` because it uses `_Static_assert` and `_Generic`.\n\n'
    printf '| Target | Compiler | Mode | Result | Notes |\n'
    printf '| --- | --- | --- | --- | --- |\n'

    local compiler mode_name mode_flag_string target_entry target_name source_file
    for compiler in "${compilers[@]}"; do
      if ! command -v "$compiler" >/dev/null 2>&1; then
        for target_entry in "${targets[@]}"; do
          target_name="${target_entry%%|*}"
          printf '| %s | %s | all | fail | compiler not found |\n' "$target_name" "$compiler"
        done
        continue
      fi
      for target_entry in "${targets[@]}"; do
        target_name="${target_entry%%|*}"
        source_file="$SRC_DIR/${target_entry##*|}"
        for i in "${!mode_names[@]}"; do
          mode_name="${mode_names[$i]}"
          mode_flag_string="${mode_flags[$i]}"
          compile_and_run "$compiler" "$mode_name" "$mode_flag_string" "$target_name" "$source_file"
        done
      done
    done
  } >"$MATRIX_FILE"
}

write_demo_outputs() {
  local compiler=""
  local mode_name="reference"
  local mode_flags="-std=c11 -O2 -fno-strict-aliasing"
  local -a compiler_candidates=(clang gcc)
  local target_entry target_name source_file out_dir binary stdout_log compile_log

  for compiler in "${compiler_candidates[@]}"; do
    if command -v "$compiler" >/dev/null 2>&1; then
      break
    fi
    compiler=""
  done

  if [[ -z "$compiler" ]]; then
    printf 'No compiler found for demo artifacts.\n' >&2
    return 1
  fi

  mkdir -p "$ARTIFACTS_DIR"
  for target_entry in "${targets[@]}"; do
    target_name="${target_entry%%|*}"
    source_file="$SRC_DIR/${target_entry##*|}"
    out_dir="$BUILD_DIR/$compiler/$mode_name/$target_name"
    binary="$out_dir/demo"
    stdout_log="$ARTIFACTS_DIR/${target_name}_stdout.txt"
    compile_log="$out_dir/compile.log"
    mkdir -p "$out_dir"
    local -a mode_array
    IFS=' ' read -r -a mode_array <<<"$mode_flags"
    if "$compiler" "${mode_array[@]}" -I"$INCLUDE_DIR" "$source_file" -o "$binary" >"$compile_log" 2>&1; then
      "$binary" >"$stdout_log" 2>&1
    else
      printf 'Failed to build %s for demo artifact with %s.\n' "$target_name" "$compiler" >&2
      return 1
    fi
  done
}

case "${1:-all}" in
  matrix)
    write_matrix
    ;;
  demo)
    write_demo_outputs
    ;;
  all)
    write_matrix
    write_demo_outputs
    ;;
  *)
    printf 'Usage: %s [matrix|demo|all]\n' "$0" >&2
    exit 2
    ;;
esac
