.PHONY: all clean a_pointer_layout bc_list_hlist e_hash fk_bit_fixedpoint ch_sort_trace

all: a_pointer_layout bc_list_hlist e_hash fk_bit_fixedpoint ch_sort_trace

a_pointer_layout:
	$(MAKE) -C labs/a_pointer_layout

bc_list_hlist:
	$(MAKE) -C labs/bc_list_hlist

e_hash:
	$(MAKE) -C labs/e_hash

fk_bit_fixedpoint:
	$(MAKE) -C labs/fk_bit_fixedpoint

ch_sort_trace:
	$(MAKE) -C labs/ch_sort_trace

clean:
	$(MAKE) -C labs/a_pointer_layout clean
	$(MAKE) -C labs/bc_list_hlist clean
	$(MAKE) -C labs/e_hash clean
	$(MAKE) -C labs/fk_bit_fixedpoint clean
	$(MAKE) -C labs/ch_sort_trace clean
